### ISSUE TITLE
WinSafe now contains all Windows API functions you need

### ISSUE THREAD

**Issue by rodrigocfd** [mcraxker/debugprotector#1]
Hi,

Just to let you know: I've been implementing a couple functions in [WinSafe](https://crates.io/crates/winsafe) lately that may be of your interest.

You're importing some functions and types from the [winapi](https://crates.io/crates/winapi) crate, which only provides unsafe bindings. I believe WinSafe now has all the bindings you need, thus allowing you to use safe Rust, and also getting rid of the (heavy) winapi dependency.

Maybe it's worth a check.

**Comment by mcraxker** [comment]
Hello,

Thanks for remind me that [WinSafe](https://crates.io/crates/winsafe) exists, im not developing this repository a lot, but looks good that crate.

For the next versión of this repository I will add the use of [WinSafe](https://crates.io/crates/winsafe) and more protection methods.

Thank you

**Comment by rodrigocfd** [comment]
Feel free to contact me if you need any help.
