### ISSUE TITLE
Publish version 0.1.4 to crates.io

### ISSUE THREAD

**Issue by lucascherzer** [mcraxker/debugprotector#4]
The latest version (0.1.4, introduced by #2 and #3) is not yet published on crates.io

If you @mcraxker could run `cargo publish` or allow me to make this change (`cargo owner --add lucascherzer`), that would be awesome :D

**Comment by mcraxker** [comment]
Yeah, i will set all commands to get you as a collaborator, if you wanna make projects withme talk with me.

**Comment by lucascherzer** [comment]
> Yeah, i will set all commands to get you as a collaborator, if you wanna make projects withme talk with me.

I see the new version on crates.io, but the new features are not available yet. Are you sure everything worked out fine when you published it?
